"""schema_initial - schema complet en une seule migration

Revision ID: 0001_schema_initial
Revises:
Create Date: 2026-09-26

Remplace les 22 migrations precedentes (0001 a 0022), squashees en une seule via
`alembic revision --autogenerate` contre une base vide (versions/ temporairement videe
pour forcer une comparaison depuis rien plutot qu'un diff incremental) - genere
directement depuis l'etat actuel des modeles SQLAlchemy (`app/core/database.Base.
metadata`), pas depuis l'historique des migrations elles-memes. Squash declenche par
un vrai bug trouve en deployant sur Render : la migration 0010 (desormais disparue)
faisait `DROP TYPE statutsoumission` puis recreait aussitot une table l'utilisant, ce
qui echouait avec `UndefinedObject: type "statutsoumission" does not exist` (Alembic
n'emettait pas le `CREATE TYPE` correspondant avant le `CREATE TABLE` dans ce cas
precis de reutilisation immediate). Comme aucune donnee reelle n'existe encore
(pilote pas en production), squasher plutot que corriger cette seule migration a
semble le choix le plus sain pour repartir sur un historique propre.

Applique et verifie contre un Postgres vide avant ce commit (upgrade head + suite de
tests complete) - voir PROJECT_MAP.md pour le detail.
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_schema_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('EP', 'ES', 'UP', name='typeetablissement'), nullable=False),
    sa.Column('statut', sa.Enum('PUBLIC', 'PRIVE', name='statutetablissement'), nullable=False),
    sa.Column('code_etablissement', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etablissements_code_etablissement'), 'etablissements', ['code_etablissement'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('login_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_temporaire', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('TUTEUR', 'ELEVE', 'ENSEIGNANT', 'ADMIN_ETABLISSEMENT', 'ADMIN_MINISTERIEL', name='roleutilisateur'), nullable=False),
    sa.Column('email_verifie', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_login_id'), 'utilisateurs', ['login_id'], unique=True)
    op.create_table('admins_etablissement',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_admins_etablissement_etablissement_id'), 'admins_etablissement', ['etablissement_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('niveau', sa.String(length=100), nullable=False),
    sa.Column('capacite', sa.Integer(), nullable=False),
    sa.Column('politique_depassement', sa.Enum('ORDRE_ARRIVEE', 'NOTES_CONCOURS', 'TIRAGE_SORT', name='politiquedepassement'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_etablissement_id'), 'classes', ['etablissement_id'], unique=False)
    op.create_table('designations_controleur',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.Enum('TRANSPORT', 'CANTINE', 'EVENEMENT', name='servicecontrole'), nullable=False),
    sa.Column('evenement_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_controleur_etablissement_id'), 'designations_controleur', ['etablissement_id'], unique=False)
    op.create_index(op.f('ix_designations_controleur_evenement_id'), 'designations_controleur', ['evenement_id'], unique=False)
    op.create_index(op.f('ix_designations_controleur_utilisateur_id'), 'designations_controleur', ['utilisateur_id'], unique=False)
    op.create_table('enseignants',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('etablissement_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('lulufiles_file_id', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etablissement_photos_etablissement_id'), 'etablissement_photos', ['etablissement_id'], unique=False)
    op.create_table('evenements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacite_max', sa.Integer(), nullable=False),
    sa.Column('prix_billet', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'ANNULE', name='statutevenement'), nullable=False),
    sa.Column('parrain_utilisateur_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['parrain_utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenements_etablissement_id'), 'evenements', ['etablissement_id'], unique=False)
    op.create_table('lignes_transport',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('capacite_par_trajet', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_transport_etablissement_id'), 'lignes_transport', ['etablissement_id'], unique=False)
    op.create_table('offres_micro_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prestataire_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('OUVERTE', 'FERMEE', name='statutoffremicrojob'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prestataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offres_micro_job_prestataire_id'), 'offres_micro_job', ['prestataire_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilisee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_utilisateur_id'), 'otp_verifications', ['utilisateur_id'], unique=False)
    op.create_table('postes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'POURVU', 'NON_POURVU', name='statutposte'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postes_etablissement_id'), 'postes', ['etablissement_id'], unique=False)
    op.create_table('referentiels_coefficients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niveau', sa.String(length=100), nullable=False),
    sa.Column('matiere', sa.String(length=100), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('VALIDE', 'PROPOSITION_EN_ATTENTE', 'REMPLACE', name='statutreferentiel'), nullable=False),
    sa.Column('etablissement_proposant_id', sa.String(length=36), nullable=True),
    sa.Column('propose_pour_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_proposant_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['propose_pour_id'], ['referentiels_coefficients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuteurs',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('piece_identite_type', sa.String(length=50), nullable=True),
    sa.Column('piece_identite_numero', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('types_acte_academique',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('pieces_requises', sa.Text(), nullable=False),
    sa.Column('condition_eligibilite', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_acte_academique_etablissement_id'), 'types_acte_academique', ['etablissement_id'], unique=False)
    op.create_table('types_repas_cantine',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('capacite_par_jour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_repas_cantine_etablissement_id'), 'types_repas_cantine', ['etablissement_id'], unique=False)
    op.create_table('visites_virtuelles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('TROIS_D', 'DRONE', name='typevisitevirtuelle'), nullable=False),
    sa.Column('lien_externe', sa.Text(), nullable=False),
    sa.Column('attestation_autorisation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visites_virtuelles_etablissement_id'), 'visites_virtuelles', ['etablissement_id'], unique=False)
    op.create_table('billets_evenement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evenement_id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.Enum('ACHETE', 'VALIDE', 'EXPIRE', 'REMBOURSE', name='statutbillet'), nullable=False),
    sa.Column('prix_paye', sa.Float(), nullable=False),
    sa.Column('paiement_confirme', sa.Boolean(), nullable=False),
    sa.Column('kkiapay_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kkiapay_transaction_id')
    )
    op.create_index(op.f('ix_billets_evenement_evenement_id'), 'billets_evenement', ['evenement_id'], unique=False)
    op.create_index(op.f('ix_billets_evenement_utilisateur_id'), 'billets_evenement', ['utilisateur_id'], unique=False)
    op.create_table('candidatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poste_id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.Enum('EN_EVALUATION', 'RETENUE', 'REJETEE', name='statutcandidature'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatures_enseignant_id'), 'candidatures', ['enseignant_id'], unique=False)
    op.create_index(op.f('ix_candidatures_poste_id'), 'candidatures', ['poste_id'], unique=False)
    op.create_table('consentements_camera_live',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eleve_utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('tuteur_id', sa.String(length=36), nullable=False),
    sa.Column('date_consentement', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eleve_utilisateur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['tuteur_id'], ['tuteurs.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentements_camera_live_eleve_utilisateur_id'), 'consentements_camera_live', ['eleve_utilisateur_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DM', 'GROUPE_CLASSE', name='typeconversation'), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_id')
    )
    op.create_table('cours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('chapitre', sa.String(length=200), nullable=False),
    sa.Column('format', sa.Enum('TEXTE', 'PDF', 'AUDIO', 'VIDEO', name='formatcours'), nullable=False),
    sa.Column('contenu_texte', sa.Text(), nullable=True),
    sa.Column('lulufiles_file_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_classe_id'), 'cours', ['classe_id'], unique=False)
    op.create_index(op.f('ix_cours_enseignant_id'), 'cours', ['enseignant_id'], unique=False)
    op.create_table('criteres_document_poste',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poste_id', sa.String(length=36), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('seuil_minimal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteres_document_poste_poste_id'), 'criteres_document_poste', ['poste_id'], unique=False)
    op.create_table('devoirs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('matiere', sa.String(length=100), nullable=False),
    sa.Column('date_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bareme', sa.Enum('RIGIDE', 'FLEXIBLE', name='baremedevoir'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoirs_classe_id'), 'devoirs', ['classe_id'], unique=False)
    op.create_index(op.f('ix_devoirs_enseignant_id'), 'devoirs', ['enseignant_id'], unique=False)
    op.create_table('eleves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('nationalite', sa.Enum('NATIONALE', 'ETRANGERE', name='nationalite'), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=True),
    sa.Column('tuteur_id', sa.String(length=36), nullable=True),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tuteur_id'], ['tuteurs.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_eleves_matricule'), 'eleves', ['matricule'], unique=True)
    op.create_table('missions_micro_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offre_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINEE_DECLAREE', 'VALIDEE', 'CONTESTEE', 'REMBOURSEE', 'PAYEE', name='statutmissionmicrojob'), nullable=False),
    sa.Column('prix_paye', sa.Float(), nullable=False),
    sa.Column('paiement_confirme', sa.Boolean(), nullable=False),
    sa.Column('kkiapay_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('date_declaration_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_limite_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_paiement_prestataire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['offre_id'], ['offres_micro_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kkiapay_transaction_id')
    )
    op.create_index(op.f('ix_missions_micro_job_client_id'), 'missions_micro_job', ['client_id'], unique=False)
    op.create_index(op.f('ix_missions_micro_job_offre_id'), 'missions_micro_job', ['offre_id'], unique=True)
    op.create_table('sessions_live',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', name='statutsessionlive'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_live_classe_id'), 'sessions_live', ['classe_id'], unique=False)
    op.create_index(op.f('ix_sessions_live_enseignant_id'), 'sessions_live', ['enseignant_id'], unique=False)
    op.create_table('tickets_cantine',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type_repas_id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('date_service', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('ACHETE', 'VALIDE', 'EXPIRE', 'REMBOURSE', name='statutticket'), nullable=False),
    sa.Column('prix_paye', sa.Float(), nullable=False),
    sa.Column('paiement_confirme', sa.Boolean(), nullable=False),
    sa.Column('kkiapay_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['type_repas_id'], ['types_repas_cantine.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kkiapay_transaction_id')
    )
    op.create_index(op.f('ix_tickets_cantine_type_repas_id'), 'tickets_cantine', ['type_repas_id'], unique=False)
    op.create_index(op.f('ix_tickets_cantine_utilisateur_id'), 'tickets_cantine', ['utilisateur_id'], unique=False)
    op.create_table('tickets_transport',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ligne_id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('date_trajet', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('ACHETE', 'VALIDE', 'EXPIRE', 'REMBOURSE', name='statutticket'), nullable=False),
    sa.Column('prix_paye', sa.Float(), nullable=False),
    sa.Column('paiement_confirme', sa.Boolean(), nullable=False),
    sa.Column('kkiapay_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ligne_id'], ['lignes_transport.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kkiapay_transaction_id')
    )
    op.create_index(op.f('ix_tickets_transport_ligne_id'), 'tickets_transport', ['ligne_id'], unique=False)
    op.create_index(op.f('ix_tickets_transport_utilisateur_id'), 'tickets_transport', ['utilisateur_id'], unique=False)
    op.create_table('bulletins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('periode', sa.String(length=50), nullable=False),
    sa.Column('moyenne_generale', sa.Float(), nullable=False),
    sa.Column('decision_passage', sa.String(length=50), nullable=True),
    sa.Column('valide_par_conseil', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulletins_classe_id'), 'bulletins', ['classe_id'], unique=False)
    op.create_index(op.f('ix_bulletins_eleve_id'), 'bulletins', ['eleve_id'], unique=False)
    op.create_table('contestations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidature_id', sa.String(length=36), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REJETEE', name='statutcontestation'), nullable=False),
    sa.Column('motif_decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contestations_candidature_id'), 'contestations', ['candidature_id'], unique=False)
    op.create_table('contestations_micro_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REJETEE', name='statutcontestationmicrojob'), nullable=False),
    sa.Column('decision_motif', sa.Text(), nullable=True),
    sa.Column('decision_par_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions_micro_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contestations_micro_job_mission_id'), 'contestations_micro_job', ['mission_id'], unique=True)
    op.create_table('contrats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidature_id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('etablissement_id', sa.String(length=36), nullable=False),
    sa.Column('syllabus', sa.Text(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE_SIGNATURE', 'SIGNE', name='statutcontrat'), nullable=False),
    sa.Column('signature_horodatage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_hash_document', sa.String(length=64), nullable=True),
    sa.Column('signature_image_lulufiles_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrats_candidature_id'), 'contrats', ['candidature_id'], unique=False)
    op.create_index(op.f('ix_contrats_enseignant_id'), 'contrats', ['enseignant_id'], unique=False)
    op.create_index(op.f('ix_contrats_etablissement_id'), 'contrats', ['etablissement_id'], unique=False)
    op.create_table('demandes_acte_academique',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('type_acte_id', sa.String(length=36), nullable=True),
    sa.Column('est_reclamation', sa.Boolean(), nullable=False),
    sa.Column('reference_evaluation', sa.String(length=200), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('SOUMISE', 'EN_TRAITEMENT', 'ACCEPTEE', 'REJETEE', name='statutdemandeacte'), nullable=False),
    sa.Column('paiement_confirme', sa.Boolean(), nullable=False),
    sa.Column('kkiapay_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('motif_rejet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['type_acte_id'], ['types_acte_academique.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kkiapay_transaction_id')
    )
    op.create_index(op.f('ix_demandes_acte_academique_eleve_id'), 'demandes_acte_academique', ['eleve_id'], unique=False)
    op.create_table('documents_candidature',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidature_id', sa.String(length=36), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('lulufiles_file_id', sa.String(length=36), nullable=True),
    sa.Column('note_ia', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'NOTE', 'ECHEC_NOTATION', name='statutdocument'), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_candidature_candidature_id'), 'documents_candidature', ['candidature_id'], unique=False)
    op.create_table('inscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE_CONSENTEMENT_PARENTAL', 'SOUMISE', 'VALIDEE', 'REJETEE', name='statutinscription'), nullable=False),
    sa.Column('consentement_parental_horodatage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_rejet', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscriptions_classe_id'), 'inscriptions', ['classe_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_eleve_id'), 'inscriptions', ['eleve_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('auteur_id', sa.String(length=36), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('masque_par', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_auteur_id'), 'messages', ['auteur_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('participants_conversation',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'utilisateur_id')
    )
    op.create_table('participations_live',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('eleve_utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('camera_autorisee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eleve_utilisateur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_live.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'eleve_utilisateur_id', name='uq_participation_live')
    )
    op.create_index(op.f('ix_participations_live_eleve_utilisateur_id'), 'participations_live', ['eleve_utilisateur_id'], unique=False)
    op.create_index(op.f('ix_participations_live_session_id'), 'participations_live', ['session_id'], unique=False)
    op.create_table('questions_devoir',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('devoir_id', sa.String(length=36), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('enonce', sa.Text(), nullable=False),
    sa.Column('bareme_reponse', sa.Text(), nullable=False),
    sa.Column('points_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['devoir_id'], ['devoirs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_devoir_devoir_id'), 'questions_devoir', ['devoir_id'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cours_id', sa.String(length=36), nullable=False),
    sa.Column('seuil_reussite', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_cours_id'), 'quiz', ['cours_id'], unique=False)
    op.create_table('sessions_el_professor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eleve_utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('cours_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['eleve_utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_utilisateur_id', 'cours_id', name='uq_session_el_professor')
    )
    op.create_index(op.f('ix_sessions_el_professor_cours_id'), 'sessions_el_professor', ['cours_id'], unique=False)
    op.create_index(op.f('ix_sessions_el_professor_eleve_utilisateur_id'), 'sessions_el_professor', ['eleve_utilisateur_id'], unique=False)
    op.create_table('soumissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('devoir_id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('EN_CORRECTION', 'CORRIGEE', 'ECHEC_CORRECTION', name='statutsoumission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['devoir_id'], ['devoirs.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soumissions_devoir_id'), 'soumissions', ['devoir_id'], unique=False)
    op.create_index(op.f('ix_soumissions_eleve_id'), 'soumissions', ['eleve_id'], unique=False)
    op.create_table('verifications_casier_judiciaire',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidature_id', sa.String(length=36), nullable=False),
    sa.Column('contenu_chiffre', sa.LargeBinary(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'CONFORME', 'NON_CONFORME', name='statutverificationcasier'), nullable=False),
    sa.Column('verifie_par_utilisateur_id', sa.String(length=36), nullable=True),
    sa.Column('date_verification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_suppression_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.ForeignKeyConstraint(['verifie_par_utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidature_id')
    )
    op.create_table('messages_el_professor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ELEVE', 'ASSISTANT', name='rolemessageelprofessor'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_el_professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_el_professor_session_id'), 'messages_el_professor', ['session_id'], unique=False)
    op.create_table('propositions_reconduction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contrat_precedent_id', sa.String(length=36), nullable=False),
    sa.Column('nouveau_contrat_id', sa.String(length=36), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REFUSEE', name='statutproposition'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrat_precedent_id'], ['contrats.id'], ),
    sa.ForeignKeyConstraint(['nouveau_contrat_id'], ['contrats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propositions_reconduction_contrat_precedent_id'), 'propositions_reconduction', ['contrat_precedent_id'], unique=False)
    op.create_table('questions_quiz',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('enonce', sa.Text(), nullable=False),
    sa.Column('choix', sa.JSON(), nullable=False),
    sa.Column('reponse_correcte_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_quiz_id'), 'questions_quiz', ['quiz_id'], unique=False)
    op.create_table('reponses_soumission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('soumission_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('texte_reponse', sa.Text(), nullable=False),
    sa.Column('points_obtenus', sa.Float(), nullable=True),
    sa.Column('commentaire_ia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions_devoir.id'], ),
    sa.ForeignKeyConstraint(['soumission_id'], ['soumissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reponses_soumission_question_id'), 'reponses_soumission', ['question_id'], unique=False)
    op.create_index(op.f('ix_reponses_soumission_soumission_id'), 'reponses_soumission', ['soumission_id'], unique=False)
    op.create_table('signalements_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('signale_par_id', sa.String(length=36), nullable=False),
    sa.Column('traite', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('traite_par_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['signale_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['traite_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signalements_message_message_id'), 'signalements_message', ['message_id'], unique=False)
    op.create_table('tentatives_quiz',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('reponses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reussie', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentatives_quiz_eleve_id'), 'tentatives_quiz', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_tentatives_quiz_quiz_id'), 'tentatives_quiz', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tentatives_quiz_quiz_id'), table_name='tentatives_quiz')
    op.drop_index(op.f('ix_tentatives_quiz_eleve_id'), table_name='tentatives_quiz')
    op.drop_table('tentatives_quiz')
    op.drop_index(op.f('ix_signalements_message_message_id'), table_name='signalements_message')
    op.drop_table('signalements_message')
    op.drop_index(op.f('ix_reponses_soumission_soumission_id'), table_name='reponses_soumission')
    op.drop_index(op.f('ix_reponses_soumission_question_id'), table_name='reponses_soumission')
    op.drop_table('reponses_soumission')
    op.drop_index(op.f('ix_questions_quiz_quiz_id'), table_name='questions_quiz')
    op.drop_table('questions_quiz')
    op.drop_index(op.f('ix_propositions_reconduction_contrat_precedent_id'), table_name='propositions_reconduction')
    op.drop_table('propositions_reconduction')
    op.drop_index(op.f('ix_messages_el_professor_session_id'), table_name='messages_el_professor')
    op.drop_table('messages_el_professor')
    op.drop_table('verifications_casier_judiciaire')
    op.drop_index(op.f('ix_soumissions_eleve_id'), table_name='soumissions')
    op.drop_index(op.f('ix_soumissions_devoir_id'), table_name='soumissions')
    op.drop_table('soumissions')
    op.drop_index(op.f('ix_sessions_el_professor_eleve_utilisateur_id'), table_name='sessions_el_professor')
    op.drop_index(op.f('ix_sessions_el_professor_cours_id'), table_name='sessions_el_professor')
    op.drop_table('sessions_el_professor')
    op.drop_index(op.f('ix_quiz_cours_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_questions_devoir_devoir_id'), table_name='questions_devoir')
    op.drop_table('questions_devoir')
    op.drop_index(op.f('ix_participations_live_session_id'), table_name='participations_live')
    op.drop_index(op.f('ix_participations_live_eleve_utilisateur_id'), table_name='participations_live')
    op.drop_table('participations_live')
    op.drop_table('participants_conversation')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_auteur_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_inscriptions_eleve_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_classe_id'), table_name='inscriptions')
    op.drop_table('inscriptions')
    op.drop_index(op.f('ix_documents_candidature_candidature_id'), table_name='documents_candidature')
    op.drop_table('documents_candidature')
    op.drop_index(op.f('ix_demandes_acte_academique_eleve_id'), table_name='demandes_acte_academique')
    op.drop_table('demandes_acte_academique')
    op.drop_index(op.f('ix_contrats_etablissement_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_enseignant_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_candidature_id'), table_name='contrats')
    op.drop_table('contrats')
    op.drop_index(op.f('ix_contestations_micro_job_mission_id'), table_name='contestations_micro_job')
    op.drop_table('contestations_micro_job')
    op.drop_index(op.f('ix_contestations_candidature_id'), table_name='contestations')
    op.drop_table('contestations')
    op.drop_index(op.f('ix_bulletins_eleve_id'), table_name='bulletins')
    op.drop_index(op.f('ix_bulletins_classe_id'), table_name='bulletins')
    op.drop_table('bulletins')
    op.drop_index(op.f('ix_tickets_transport_utilisateur_id'), table_name='tickets_transport')
    op.drop_index(op.f('ix_tickets_transport_ligne_id'), table_name='tickets_transport')
    op.drop_table('tickets_transport')
    op.drop_index(op.f('ix_tickets_cantine_utilisateur_id'), table_name='tickets_cantine')
    op.drop_index(op.f('ix_tickets_cantine_type_repas_id'), table_name='tickets_cantine')
    op.drop_table('tickets_cantine')
    op.drop_index(op.f('ix_sessions_live_enseignant_id'), table_name='sessions_live')
    op.drop_index(op.f('ix_sessions_live_classe_id'), table_name='sessions_live')
    op.drop_table('sessions_live')
    op.drop_index(op.f('ix_missions_micro_job_offre_id'), table_name='missions_micro_job')
    op.drop_index(op.f('ix_missions_micro_job_client_id'), table_name='missions_micro_job')
    op.drop_table('missions_micro_job')
    op.drop_index(op.f('ix_eleves_matricule'), table_name='eleves')
    op.drop_table('eleves')
    op.drop_index(op.f('ix_devoirs_enseignant_id'), table_name='devoirs')
    op.drop_index(op.f('ix_devoirs_classe_id'), table_name='devoirs')
    op.drop_table('devoirs')
    op.drop_index(op.f('ix_criteres_document_poste_poste_id'), table_name='criteres_document_poste')
    op.drop_table('criteres_document_poste')
    op.drop_index(op.f('ix_cours_enseignant_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_classe_id'), table_name='cours')
    op.drop_table('cours')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consentements_camera_live_eleve_utilisateur_id'), table_name='consentements_camera_live')
    op.drop_table('consentements_camera_live')
    op.drop_index(op.f('ix_candidatures_poste_id'), table_name='candidatures')
    op.drop_index(op.f('ix_candidatures_enseignant_id'), table_name='candidatures')
    op.drop_table('candidatures')
    op.drop_index(op.f('ix_billets_evenement_utilisateur_id'), table_name='billets_evenement')
    op.drop_index(op.f('ix_billets_evenement_evenement_id'), table_name='billets_evenement')
    op.drop_table('billets_evenement')
    op.drop_index(op.f('ix_visites_virtuelles_etablissement_id'), table_name='visites_virtuelles')
    op.drop_table('visites_virtuelles')
    op.drop_index(op.f('ix_types_repas_cantine_etablissement_id'), table_name='types_repas_cantine')
    op.drop_table('types_repas_cantine')
    op.drop_index(op.f('ix_types_acte_academique_etablissement_id'), table_name='types_acte_academique')
    op.drop_table('types_acte_academique')
    op.drop_table('tuteurs')
    op.drop_table('referentiels_coefficients')
    op.drop_index(op.f('ix_postes_etablissement_id'), table_name='postes')
    op.drop_table('postes')
    op.drop_index(op.f('ix_otp_verifications_utilisateur_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_offres_micro_job_prestataire_id'), table_name='offres_micro_job')
    op.drop_table('offres_micro_job')
    op.drop_index(op.f('ix_lignes_transport_etablissement_id'), table_name='lignes_transport')
    op.drop_table('lignes_transport')
    op.drop_index(op.f('ix_evenements_etablissement_id'), table_name='evenements')
    op.drop_table('evenements')
    op.drop_index(op.f('ix_etablissement_photos_etablissement_id'), table_name='etablissement_photos')
    op.drop_table('etablissement_photos')
    op.drop_table('enseignants')
    op.drop_index(op.f('ix_designations_controleur_utilisateur_id'), table_name='designations_controleur')
    op.drop_index(op.f('ix_designations_controleur_evenement_id'), table_name='designations_controleur')
    op.drop_index(op.f('ix_designations_controleur_etablissement_id'), table_name='designations_controleur')
    op.drop_table('designations_controleur')
    op.drop_index(op.f('ix_classes_etablissement_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_admins_etablissement_etablissement_id'), table_name='admins_etablissement')
    op.drop_table('admins_etablissement')
    op.drop_index(op.f('ix_utilisateurs_login_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_etablissements_code_etablissement'), table_name='etablissements')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
